apiVersion: apps/v1
kind: Deployment
metadata:
  name: logguardian
  namespace: aiops-demo
  labels:
    app: logguardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logguardian
  template:
    metadata:
      labels:
        app: logguardian
    spec:
      serviceAccountName: logguardian-sa
      containers:
        - name: logguardian
          image: logguardian:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: LOGGUARDIAN_NAMESPACE
              value: "aiops-demo"
            - name: LOGGUARDIAN_LABEL_SELECTOR
              value: "app in (payment-service,order-service)"
            - name: MONGODB_URI
              value: "mongodb://mongo.aiops-demo.svc.cluster.local:27017/logguardian"
            # AI disabled by default for PoC; enable when ready
            - name: LOGGUARDIAN_AI_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: logguardian
  namespace: aiops-demo
spec:
  selector:
    app: logguardian
  ports:
    - name: http
      port: 8087
      targetPort: 8087
