apiVersion: v1
kind: ServiceAccount
metadata:
  name: logguardian-sa
  namespace: aiops-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logguardian-role
  namespace: aiops-demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logguardian-rb
  namespace: aiops-demo
subjects:
  - kind: ServiceAccount
    name: logguardian-sa
    namespace: aiops-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logguardian-role
