services:
  mongo:
    image: mongo:7
    container_name: logguardian-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logguardian
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
